import type { NextPage } from "next";
import Head from "next/head";
import { NavBar } from "../components/Navbar.tsx/NavBar";
import { Container, Row, Grid } from "@nextui-org/react";
import { DaoList } from "../components/Dao/DaoList";
import { DaoForm } from "../components/Dao/DaoForm";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Lang DAO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <NavBar active="home" />
          <Row>
            <Grid.Container gap={2} justify="center">
              <Grid md={6} lg={6} xs={12}>
                <DaoList/>
              </Grid>
              <Grid md={6} lg={6} xs={12}>
                <DaoForm/>
              </Grid>
            </Grid.Container>
          </Row>
        </Container>
      </main>
    </>
  );
};

export default Home;
